# -*- mode: conf; -*-

top-title: 临高启明

author:
  name: lingaoqiming
  email: lingaoqiming2104@sina.com
  github: lingaoqiming

markdown: rdiscount
permalink:  none
production_url: http://blog.yssbox.com/lingaoqiming.github.io/
baseurl: /lingaoqiming.github.io
img_url: http://lingaoqiming.github.io//images

collections:
  characters:
    output: true
